name: Build umodel Linux i386
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install 32bit build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make git perl gcc-multilib
          sudo apt-get install -y libsdl2-dev:i386 zlib1g-dev:i386 libpng-dev:i386

    

      - name: Compile i386
        run: |
          chmod +x build.sh
          # 强制gcc生成32位代码，传入CFLAGS
          export CFLAGS="-m32"
          export CXXFLAGS="-m32"
          export LDFLAGS="-m32"
          ./build.sh linux

      - name: Upload i386 binary
        uses: actions/upload-artifact@v4
        with:
          name: umodel-linux-i386
          path: umodel
